/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "lib.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int sslvpn_get_version(char* in_json, char** out_json);
extern int sslvpn_check_status(char* in_json, char** out_json);
extern int sslvpn_gen_default_cfg(char* in_json, char** out_json);
extern int sslvpn_restart_service(char* in_json, char** out_json);
extern int sslvpn_set_cfg(char* in_json, char** out_json);
extern int sslvpn_get_cfg(char* in_json, char** out_json);
extern int sslvpn_set_user(char* in_json, char** out_json);
extern int sslvpn_get_user(char* in_json, char** out_json);
extern int sslvpn_set_resource(char* in_json, char** out_json);
extern int sslvpn_get_resource(char* in_json, char** out_json);
extern int sslvpn_set_authority(char* in_json, char** out_json);
extern int sslvpn_get_authority(char* in_json, char** out_json);
extern int plugin_set_cert_and_other(char* in_json, char** out_json);
extern int plugin_get_cert_and_other(char* in_json, char** out_json);
extern int nanomq_get_cfg(char* in_json, char** out_json);
extern int nanomq_set_cfg(char* in_json, char** out_json);
extern int mqtt_auth_get_cfg(char* in_json, char** out_json);
extern int mqtt_auth_set_cfg(char* in_json, char** out_json);
extern int nanomq_start(char* in_json, char** out_json);
extern int nanomq_stop(char* in_json, char** out_json);
extern int nanomq_restart(char* in_json, char** out_json);
extern int nanomq_status(char* in_json, char** out_json);
extern int iotdevmgr_get_iot(char* in_json, char** out_json);
extern int iotdevmgr_del_iot(char* in_json, char** out_json);

#ifdef __cplusplus
}
#endif
