# 应用配置
app:
  name: "iotdev_manager"
  version: "1.0.0"
  port: 8080

# 日志配置
log:
  level: "info"  # debug, info, warn, error, fatal
  file: "logs/iodev_manager.log"
  console: true

mqtt:
  broker: "tls://localhost:1883"
  tls:
    caCert: "ca.crt"
    clientCert: "client.crt"
    clientKey: "client.key"
  topic: "test/topic"
  clientID: "iotdev_manager"
  username: "mqttuser"
  password: "mqttpassword"
  qos: 0
  keepAlive: 60
  reconnectInterval: 5
  maxReconnectAttempts: 3
